version: '3.8'
services:
  voice_commands_api:
    build: ./voice-commands-api
    ports:
      - "5000:5000"
    depends_on:
      - db

  navigation_api:
    build: ./navigation-api
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    build: ./database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
